completed level 1 and 2 of node-fs-readfile exercise
hsu-isaac/c0621-code-solutions pull request #81
Opened 2021-08-11 21:58 UTC by hsu-isaac

![image](https://user-images.githubusercontent.com/85271794/129108859-91f1a63f-9d9b-4c21-b23f-7be2bab6c340.png)

2021-08-11 22:20 UTC, thebearingedge requested changes

2021-08-11 22:20 UTC, thebearingedge commented on node-fs-readfile/cat.js
> +  } catch (err) {}
Why the `try/catch`? If there's an error reading the file, unfortunately, the error will not be thrown synchronously. You will need a mind shift for this one as you cannot guarantee that the reads will complete in the order you start them.

2021-08-12 00:01 UTC, thebearingedge requested changes
Please include a video of the level three working. I'm leaving this review to update my records.

2021-08-12 00:43 UTC, hsu-isaac commented
Never mind, it doesn't work - I guess I just got lucky with the tests I ran earlier

2021-08-12 20:31 UTC, hsu-isaac commented
![node-fs-readfile](https://user-images.githubusercontent.com/85271794/129265470-2e9b8cb1-3f75-4c34-b1ab-587476412dfd.gif)

2021-08-12 20:32 UTC, thebearingedge requested changes
Ok, good, you are on the right track, but we can simplify this a bit and remove a bunch of the code

- create an empty array
- start a counter
- loop through your arguments
- start a readfile for every argument
- when each one finishes
  - increment your counter
  - add the data to the array at the same index as the argument
  - check if the counter is done and if it is
    - print each value store in the array

2021-08-13 00:39 UTC, thebearingedge approved these changes

2021-08-13 00:39 UTC, merged